import type { Metadata } from "next";
import { Anton,Inter } from "next/font/google";
import "./globals.css";

const anton = Anton({
  variable: "--font-anton-sans",
  subsets: ["latin"],
  weight:"400"
});

const inter = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${inter.variable} antialiased bg-background text-gray-300 font-inter`}
      >
        {children}
      </body>
    </html>
  );
}
